
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cert-ocp4
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-2 Data-in-transit
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: CertificatePolicy
      metadata:
        name: openshift-cert-policy
      spec:
        namespaceSelector:
          include:
          - openshift-service-ca-operator
          - openshift-service-ca
          - openshift-operator-lifecycle-manager
          - openshift-apiserver
          - openshift-apiserver-operator
          - openshift-authentication
          - openshift-authentication-operator
          - openshift-cluster-machine-approver
          - openshift-cluster-samples-operator
          - openshift-cluster-storage-operator
          - openshift-cluster-version
          - openshift-config-managed
          - openshift-config-operator
          - openshift-console
          - openshift-console-operator
          - openshift-controller-manager
          - openshift-controller-manager-operator
          - openshift-dns
          - openshift-dns-operator
          - openshift-etcd
          - openshift-etcd-operator
          - openshift-image-registry
          - openshift-ingress
          - openshift-ingress-operator
          - openshift-insights
          - openshift-kube-apiserver
          - openshift-kube-apiserver-operator
          - openshift-kube-controller-manager
          - openshift-kube-controller-manager-operator
          - openshift-kube-scheduler
          - openshift-kube-scheduler-operator
          - openshift-kube-storage-version-migrator-operator
          - openshift-machine-api
          - openshift-machine-config-operator
          - openshift-marketplace
          - openshift-monitoring
          - openshift-multus
        remediationAction: inform
        minimumDuration: 720h
        minimumCADuration: 400h
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cert-ocp4
placementRef:
  name: placement-policy-cert-ocp4
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cert-ocp4
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cert-ocp4
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
